# DataGeneratorCLI configuration.
datagen:
  pg_prewarm: True
  pg_analyze: True
  benchmarks: [tpcc]        # Benchmarks include: [auctionmark, epinions, seats, sibench, smallbank, tatp, tpcc, tpch, twitter, voter, wikipedia, ycsb]
  log_level: DEBUG
  debug: False
  param_sweep:
    url: ["jdbc:postgresql://localhost:5432/benchbase?preferQueryMode=extended"]
    isolation: [TRANSACTION_READ_COMMITTED]
    scalefactor: [0.01, 0.1]
    terminals: [1]
    works.work.rate: [10000]
    works.work.time: [60]
